<html>
<head>
<title>TestNG:  ETL Test</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>ETL Test</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>0/10/0</td>
</tr><tr>
<td>Started on:</td><td>Wed May 28 19:13:32 IST 2014</td>
</tr>
<tr><td>Total time:</td><td>28 seconds (28146 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.sapphire.etl.AERSDemoVerify.demoCASE_ID()'><b>demoCASE_ID</b><br>Test class: com.sapphire.etl.AERSDemoVerify<br/>
<a href="#Output-5143025" onClick='toggleBox("Output-5143025", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-5143025" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-5143025">
SELECT coun(*) FROM aers_demo where case_id is null<br/>
Expected : null<br/>
Actual : null<br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: SELECT coun(*) FROM aers_demo where case_id is null
	at com.sapphire.etl.AERSDemoVerify.demoCASE_ID(AERSDemoVerify.java:141)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &apos;*) FROM aers_demo where case_id is null&apos; at line 1
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2618)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2568)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1557)
	at com.sapphire.etl.AERSDemoVerify.demoCASE_ID(AERSDemoVerify.java:128)
	... 24 more
... Removed 29 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace5143025", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace5143025'><pre>java.lang.AssertionError: SELECT coun(*) FROM aers_demo where case_id is null
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCASE_ID(AERSDemoVerify.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &apos;*) FROM aers_demo where case_id is null&apos; at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2618)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2568)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1557)
	at com.sapphire.etl.AERSDemoVerify.demoCASE_ID(AERSDemoVerify.java:128)
	... 24 more
</pre></div></td>
<td>0</td>
<td>com.sapphire.etl.AERSDemoVerify@1893efe</td></tr>
<tr>
<td title='com.sapphire.etl.AERSDemoVerify.demoCaseAgeCode()'><b>demoCaseAgeCode</b><br>Test class: com.sapphire.etl.AERSDemoVerify<br/>
<a href="#Output-2208288" onClick='toggleBox("Output-2208288", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-2208288" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-2208288">
SELECT distinct age_code FROM aers_demo<br/>
Expected : [YR, MON, WK, DY, HR, DEC, MIN, SEC, '']<br/>
Actual : [YR,  , MON, WK, DY, HR, DEC, M, F, 64, SEC, MIN, 85]<br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: SELECT distinct age_code FROM aers_demo
	at com.sapphire.etl.AERSDemoVerify.demoCaseAgeCode(AERSDemoVerify.java:314)
Caused by: java.lang.AssertionError: null: lists don&apos;t have the same size expected [9] but found [13]
	at com.sapphire.etl.AERSDemoVerify.demoCaseAgeCode(AERSDemoVerify.java:309)
	... 24 more
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace2208288", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace2208288'><pre>java.lang.AssertionError: SELECT distinct age_code FROM aers_demo
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseAgeCode(AERSDemoVerify.java:314)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: null: lists don&apos;t have the same size expected [9] but found [13]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:537)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.sapphire.etl.AERSDemoVerify.demoCaseAgeCode(AERSDemoVerify.java:309)
	... 24 more
</pre></div></td>
<td>8</td>
<td>com.sapphire.etl.AERSDemoVerify@1893efe</td></tr>
<tr>
<td title='com.sapphire.etl.AERSDemoVerify.demoCaseAgeGroup()'><b>demoCaseAgeGroup</b><br>Test class: com.sapphire.etl.AERSDemoVerify<br/>
<a href="#Output-15206466" onClick='toggleBox("Output-15206466", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-15206466" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-15206466">
SELECT count(*) FROM aers_demo where std_age_group = 'Not Available' AND age != '' AND age_code != '' AND age not like ('%-%') AND age not like ('%.%') AND age != 0 AND age != 00<br/>
Expected : []<br/>
Actual : []<br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: SELECT count(*) FROM aers_demo where std_age_group = &apos;Not Available&apos; AND age != &apos;&apos; AND age_code != &apos;&apos; AND age not like (&apos;%-%&apos;) AND age not like (&apos;%.%&apos;) AND age != 0 AND age != 00
	at com.sapphire.etl.AERSDemoVerify.demoCaseAgeGroup(AERSDemoVerify.java:351)
Caused by: java.sql.SQLException: Column Index out of range, 2 &gt; 1. 
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ResultSetImpl.checkColumnBounds(ResultSetImpl.java:818)
	at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5651)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5570)
	at com.sapphire.etl.AERSDemoVerify.demoCaseAgeGroup(AERSDemoVerify.java:340)
	... 24 more
... Removed 25 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace15206466", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace15206466'><pre>java.lang.AssertionError: SELECT count(*) FROM aers_demo where std_age_group = &apos;Not Available&apos; AND age != &apos;&apos; AND age_code != &apos;&apos; AND age not like (&apos;%-%&apos;) AND age not like (&apos;%.%&apos;) AND age != 0 AND age != 00
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseAgeGroup(AERSDemoVerify.java:351)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.sql.SQLException: Column Index out of range, 2 &gt; 1. 
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ResultSetImpl.checkColumnBounds(ResultSetImpl.java:818)
	at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5651)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5570)
	at com.sapphire.etl.AERSDemoVerify.demoCaseAgeGroup(AERSDemoVerify.java:340)
	... 24 more
</pre></div></td>
<td>4</td>
<td>com.sapphire.etl.AERSDemoVerify@1893efe</td></tr>
<tr>
<td title='com.sapphire.etl.AERSDemoVerify.demoCaseGenderCode()'><b>demoCaseGenderCode</b><br>Test class: com.sapphire.etl.AERSDemoVerify<br/>
<a href="#Output-30146205" onClick='toggleBox("Output-30146205", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-30146205" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-30146205">
SELECT distinct gender_code FROM aers_demo<br/>
Expected : [F, M, UNK, NS, U, '']<br/>
Actual : [F,  , M, UNK, NS, null, YR, N, Y, U]<br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: SELECT distinct gender_code FROM aers_demo
	at com.sapphire.etl.AERSDemoVerify.demoCaseGenderCode(AERSDemoVerify.java:207)
Caused by: java.lang.AssertionError: null: lists don&apos;t have the same size expected [6] but found [10]
	at com.sapphire.etl.AERSDemoVerify.demoCaseGenderCode(AERSDemoVerify.java:202)
	... 24 more
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace30146205", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace30146205'><pre>java.lang.AssertionError: SELECT distinct gender_code FROM aers_demo
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseGenderCode(AERSDemoVerify.java:207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: null: lists don&apos;t have the same size expected [6] but found [10]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:537)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.sapphire.etl.AERSDemoVerify.demoCaseGenderCode(AERSDemoVerify.java:202)
	... 24 more
</pre></div></td>
<td>8</td>
<td>com.sapphire.etl.AERSDemoVerify@1893efe</td></tr>
<tr>
<td title='com.sapphire.etl.AERSDemoVerify.demoCaseGenderDEC()'><b>demoCaseGenderDEC</b><br>Test class: com.sapphire.etl.AERSDemoVerify<br/>
<a href="#Output-3199106" onClick='toggleBox("Output-3199106", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-3199106" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-3199106">
SELECT distinct gender_dec FROM aers_demo<br/>
Expected : null<br/>
Actual : []<br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: SELECT distinct gender_dec FROM aers_demo
	at com.sapphire.etl.AERSDemoVerify.demoCaseGenderDEC(AERSDemoVerify.java:242)
Caused by: java.sql.SQLException: Column Index out of range, 2 &gt; 1. 
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ResultSetImpl.checkColumnBounds(ResultSetImpl.java:818)
	at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5651)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5570)
	at com.sapphire.etl.AERSDemoVerify.demoCaseGenderDEC(AERSDemoVerify.java:228)
	... 24 more
... Removed 25 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace3199106", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace3199106'><pre>java.lang.AssertionError: SELECT distinct gender_dec FROM aers_demo
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseGenderDEC(AERSDemoVerify.java:242)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.sql.SQLException: Column Index out of range, 2 &gt; 1. 
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ResultSetImpl.checkColumnBounds(ResultSetImpl.java:818)
	at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5651)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5570)
	at com.sapphire.etl.AERSDemoVerify.demoCaseGenderDEC(AERSDemoVerify.java:228)
	... 24 more
</pre></div></td>
<td>0</td>
<td>com.sapphire.etl.AERSDemoVerify@1893efe</td></tr>
<tr>
<td title='com.sapphire.etl.AERSDemoVerify.demoCaseSeriousness()'><b>demoCaseSeriousness</b><br>Test class: com.sapphire.etl.AERSDemoVerify<br/>
<a href="#Output-17320380" onClick='toggleBox("Output-17320380", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-17320380" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-17320380">
SELECT count(*) FROM aers_demo where seriousness = 1 and ( outc_death= 0 and  outc_life_threat =0 and outc_hosp =0 and outc_disability=0 and outc_cong_anomaly=0  and outc_reqd_interv=0 and outc_other=0 and outc_none=0 and outc_rec=0 and outc_rx=0)<br/>
Expected : null<br/>
Actual : []<br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: SELECT count(*) FROM aers_demo where seriousness = 1 and ( outc_death= 0 and  outc_life_threat =0 and outc_hosp =0 and outc_disability=0 and outc_cong_anomaly=0  and outc_reqd_interv=0 and outc_other=0 and outc_none=0 and outc_rec=0 and outc_rx=0)
	at com.sapphire.etl.AERSDemoVerify.demoCaseSeriousness(AERSDemoVerify.java:275)
Caused by: java.sql.SQLException: Column Index out of range, 12 &gt; 1. 
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ResultSetImpl.checkColumnBounds(ResultSetImpl.java:818)
	at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5651)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5570)
	at com.sapphire.etl.AERSDemoVerify.demoCaseSeriousness(AERSDemoVerify.java:265)
	... 24 more
... Removed 25 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace17320380", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace17320380'><pre>java.lang.AssertionError: SELECT count(*) FROM aers_demo where seriousness = 1 and ( outc_death= 0 and  outc_life_threat =0 and outc_hosp =0 and outc_disability=0 and outc_cong_anomaly=0  and outc_reqd_interv=0 and outc_other=0 and outc_none=0 and outc_rec=0 and outc_rx=0)
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseSeriousness(AERSDemoVerify.java:275)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.sql.SQLException: Column Index out of range, 12 &gt; 1. 
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ResultSetImpl.checkColumnBounds(ResultSetImpl.java:818)
	at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5651)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5570)
	at com.sapphire.etl.AERSDemoVerify.demoCaseSeriousness(AERSDemoVerify.java:265)
	... 24 more
</pre></div></td>
<td>6</td>
<td>com.sapphire.etl.AERSDemoVerify@1893efe</td></tr>
<tr>
<td title='com.sapphire.etl.AERSDemoVerify.demoCaseValidFrom()'><b>demoCaseValidFrom</b><br>Test class: com.sapphire.etl.AERSDemoVerify<br/>
<a href="#Output-22522451" onClick='toggleBox("Output-22522451", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-22522451" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-22522451">
SELECT count(*) FROM aers_demo where valid_from is null<br/>
Expected : []<br/>
Actual : [0]<br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: SELECT count(*) FROM aers_demo where valid_from is null
	at com.sapphire.etl.AERSDemoVerify.demoCaseValidFrom(AERSDemoVerify.java:44)
Caused by: java.lang.AssertionError: null: lists don&apos;t have the same size expected [0] but found [1]
	at com.sapphire.etl.AERSDemoVerify.demoCaseValidFrom(AERSDemoVerify.java:39)
	... 24 more
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace22522451", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace22522451'><pre>java.lang.AssertionError: SELECT count(*) FROM aers_demo where valid_from is null
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseValidFrom(AERSDemoVerify.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: null: lists don&apos;t have the same size expected [0] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:537)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.sapphire.etl.AERSDemoVerify.demoCaseValidFrom(AERSDemoVerify.java:39)
	... 24 more
</pre></div></td>
<td>0</td>
<td>com.sapphire.etl.AERSDemoVerify@1893efe</td></tr>
<tr>
<td title='com.sapphire.etl.AERSDemoVerify.demoCaseValidTo()'><b>demoCaseValidTo</b><br>Test class: com.sapphire.etl.AERSDemoVerify<br/>
<a href="#Output-12430225" onClick='toggleBox("Output-12430225", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-12430225" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-12430225">
SELECT count(*) FROM aers_demo where valid_to is null<br/>
Expected : []<br/>
Actual : [13]<br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: SELECT count(*) FROM aers_demo where valid_to is null
	at com.sapphire.etl.AERSDemoVerify.demoCaseValidTo(AERSDemoVerify.java:76)
Caused by: java.lang.AssertionError: null: lists don&apos;t have the same size expected [0] but found [1]
	at com.sapphire.etl.AERSDemoVerify.demoCaseValidTo(AERSDemoVerify.java:71)
	... 24 more
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace12430225", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace12430225'><pre>java.lang.AssertionError: SELECT count(*) FROM aers_demo where valid_to is null
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseValidTo(AERSDemoVerify.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: null: lists don&apos;t have the same size expected [0] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:537)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.sapphire.etl.AERSDemoVerify.demoCaseValidTo(AERSDemoVerify.java:71)
	... 24 more
</pre></div></td>
<td>0</td>
<td>com.sapphire.etl.AERSDemoVerify@1893efe</td></tr>
<tr>
<td title='com.sapphire.etl.AERSDemoVerify.demoFDA_date()'><b>demoFDA_date</b><br>Test class: com.sapphire.etl.AERSDemoVerify<br/>
<a href="#Output-2478770" onClick='toggleBox("Output-2478770", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-2478770" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-2478770">
SELECT count(*) FROM aers_demo where fda_date is null<br/>
Expected : []<br/>
Actual : [0]<br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: SELECT count(*) FROM aers_demo where fda_date is null
	at com.sapphire.etl.AERSDemoVerify.demoFDA_date(AERSDemoVerify.java:171)
Caused by: java.lang.AssertionError: null: lists don&apos;t have the same size expected [0] but found [1]
	at com.sapphire.etl.AERSDemoVerify.demoFDA_date(AERSDemoVerify.java:166)
	... 24 more
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace2478770", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace2478770'><pre>java.lang.AssertionError: SELECT count(*) FROM aers_demo where fda_date is null
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoFDA_date(AERSDemoVerify.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: null: lists don&apos;t have the same size expected [0] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:537)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.sapphire.etl.AERSDemoVerify.demoFDA_date(AERSDemoVerify.java:166)
	... 24 more
</pre></div></td>
<td>0</td>
<td>com.sapphire.etl.AERSDemoVerify@1893efe</td></tr>
<tr>
<td title='com.sapphire.etl.AERSDemoVerify.demoISR_ID()'><b>demoISR_ID</b><br>Test class: com.sapphire.etl.AERSDemoVerify<br/>
<a href="#Output-14161796" onClick='toggleBox("Output-14161796", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-14161796" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-14161796">
SELECT count(*) FROM aers_demo where isr_id is null<br/>
Expected : []<br/>
Actual : [0]<br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: SELECT count(*) FROM aers_demo where isr_id is null
	at com.sapphire.etl.AERSDemoVerify.demoISR_ID(AERSDemoVerify.java:109)
Caused by: java.lang.AssertionError: null: lists don&apos;t have the same size expected [0] but found [1]
	at com.sapphire.etl.AERSDemoVerify.demoISR_ID(AERSDemoVerify.java:104)
	... 24 more
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace14161796", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace14161796'><pre>java.lang.AssertionError: SELECT count(*) FROM aers_demo where isr_id is null
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoISR_ID(AERSDemoVerify.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: null: lists don&apos;t have the same size expected [0] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:537)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.sapphire.etl.AERSDemoVerify.demoISR_ID(AERSDemoVerify.java:104)
	... 24 more
</pre></div></td>
<td>0</td>
<td>com.sapphire.etl.AERSDemoVerify@1893efe</td></tr>
</table><p>
</body>
</html>