<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PDWIVEDI" name="Database Test on Win7" tests="18" failures="9" timestamp="30 Jun 2014 15:11:04 GMT" time="5.332" errors="0">
  <testcase name="drugCleaned_GenericName" time="0.4" classname="com.sapphire.etl.AERS_DRUGS">
    <failure type="java.lang.AssertionError" message="SELECT count(*) FROM aers.aers_drugs where drug_cleaned is not null and generic_name is null or generic_name=&amp;apos;&amp;apos;">
      <![CDATA[java.lang.AssertionError: SELECT count(*) FROM aers.aers_drugs where drug_cleaned is not null and generic_name is null or generic_name=''
	at com.sapphire.etl.AERS_DRUGS.drugCleaned_GenericName(AERSDrugVerify.java:139)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- drugCleaned_GenericName -->
  <testcase name="drugCleaned_Null" time="0.033" classname="com.sapphire.etl.AERS_DRUGS">
    <failure type="java.lang.AssertionError" message="SELECT count(*) FROM aers.aers_drugs where drug_cleaned is null">
      <![CDATA[java.lang.AssertionError: SELECT count(*) FROM aers.aers_drugs where drug_cleaned is null
	at com.sapphire.etl.AERS_DRUGS.drugCleaned_Null(AERSDrugVerify.java:179)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.AssertionError: Lists differ at element [0]: 0 != 1960 expected [0] but found [1960]
	at com.sapphire.etl.AERS_DRUGS.drugCleaned_Null(AERSDrugVerify.java:169)
	... 21 more
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- drugCleaned_Null -->
  <testcase name="drugRole_Code" time="0.027" classname="com.sapphire.etl.AERS_DRUGS"/>
  <testcase name="drugRole_Decode" time="0.027" classname="com.sapphire.etl.AERS_DRUGS"/>
  <testcase name="demoCASE_ID" time="0.031" classname="com.sapphire.etl.AERS_DEMO"/>
  <testcase name="demoCaseAgeCode" time="0.028" classname="com.sapphire.etl.AERS_DEMO">
    <failure type="java.lang.AssertionError" message="SELECT distinct age_code FROM aers_demo">
      <![CDATA[java.lang.AssertionError: SELECT distinct age_code FROM aers_demo
	at com.sapphire.etl.AERS_DEMO.demoCaseAgeCode(AERSDemoVerify.java:347)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.AssertionError: null: lists don't have the same size expected [9] but found [13]
	at com.sapphire.etl.AERS_DEMO.demoCaseAgeCode(AERSDemoVerify.java:338)
	... 21 more
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- demoCaseAgeCode -->
  <testcase name="demoCaseAgeGroup" time="4.414" classname="com.sapphire.etl.AERS_DEMO">
    <failure type="java.lang.AssertionError" message="SELECT count(*) FROM aers_demo where std_age_group = &amp;apos;Not Available&amp;apos; AND age != &amp;apos;&amp;apos; AND age_code != &amp;apos;&amp;apos; AND age not like (&amp;apos;%-%&amp;apos;) AND age not like (&amp;apos;%.%&amp;apos;) AND age != 0 AND age != 00">
      <![CDATA[java.lang.AssertionError: SELECT count(*) FROM aers_demo where std_age_group = 'Not Available' AND age != '' AND age_code != '' AND age not like ('%-%') AND age not like ('%.%') AND age != 0 AND age != 00
	at com.sapphire.etl.AERS_DEMO.demoCaseAgeGroup(AERSDemoVerify.java:388)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.AssertionError: Lists differ at element [0]: 0 != 631 expected [0] but found [631]
	at com.sapphire.etl.AERS_DEMO.demoCaseAgeGroup(AERSDemoVerify.java:379)
	... 21 more
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- demoCaseAgeGroup -->
  <testcase name="demoCaseGender" time="0.031" classname="com.sapphire.etl.AERS_DEMO"/>
  <testcase name="demoCaseGenderCode" time="0.031" classname="com.sapphire.etl.AERS_DEMO">
    <failure type="java.lang.AssertionError" message="SELECT distinct gender_code FROM aers_demo">
      <![CDATA[java.lang.AssertionError: SELECT distinct gender_code FROM aers_demo
	at com.sapphire.etl.AERS_DEMO.demoCaseGenderCode(AERSDemoVerify.java:217)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.AssertionError: null: lists don't have the same size expected [6] but found [10]
	at com.sapphire.etl.AERS_DEMO.demoCaseGenderCode(AERSDemoVerify.java:208)
	... 21 more
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- demoCaseGenderCode -->
  <testcase name="demoCaseSeriousness" time="0.056" classname="com.sapphire.etl.AERS_DEMO"/>
  <testcase name="demoCaseValidFrom" time="0.029" classname="com.sapphire.etl.AERS_DEMO"/>
  <testcase name="demoCaseValidTo" time="0.029" classname="com.sapphire.etl.AERS_DEMO">
    <failure type="java.lang.AssertionError" message="SELECT count(*) FROM aers_demo where valid_to is null">
      <![CDATA[java.lang.AssertionError: SELECT count(*) FROM aers_demo where valid_to is null
	at com.sapphire.etl.AERS_DEMO.demoCaseValidTo(AERSDemoVerify.java:92)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.AssertionError: Lists differ at element [0]: 0 != 13 expected [0] but found [13]
	at com.sapphire.etl.AERS_DEMO.demoCaseValidTo(AERSDemoVerify.java:83)
	... 21 more
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- demoCaseValidTo -->
  <testcase name="demoFDA_date" time="0.027" classname="com.sapphire.etl.AERS_DEMO"/>
  <testcase name="reactionPtCodeNotNull" time="0.026" classname="com.sapphire.etl.AERS_REACTIONS"/>
  <testcase name="reactionPtNameNotNull" time="0.026" classname="com.sapphire.etl.AERS_REACTIONS"/>
  <testcase name="reactionVBM" time="0.027" classname="com.sapphire.etl.AERS_REACTIONS">
    <failure type="java.lang.AssertionError" message="select count(distinct reaction_vbm) from aers.aers_reactions where pt_name is null">
      <![CDATA[java.lang.AssertionError: select count(distinct reaction_vbm) from aers.aers_reactions where pt_name is null
	at com.sapphire.etl.AERS_REACTIONS.reactionVBM(AERSReactionVerify.java:54)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.AssertionError: Lists differ at element [0]: 0 != 41 expected [0] but found [41]
	at com.sapphire.etl.AERS_REACTIONS.reactionVBM(AERSReactionVerify.java:45)
	... 21 more
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- reactionVBM -->
  <testcase name="AERSCaseCountDemo" time="0.034" classname="com.sapphire.etl.AERS_RECORD_COUNTS">
    <failure type="java.lang.AssertionError" message="SELECT fda_rel_qtr,count(*) FROM aers_demo group by fda_rel_qtr">
      <![CDATA[java.lang.AssertionError: SELECT fda_rel_qtr,count(*) FROM aers_demo group by fda_rel_qtr
	at com.sapphire.etl.AERS_RECORD_COUNTS.AERSCaseCountDemo(CaseCountInQtr.java:92)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.AssertionError: Collections not equal: expected: null and actual: [00Q1, 41758, 00Q2, 38529, 00Q3, 48361, 00Q4, 49215, 01Q1, 50517, 01Q2, 43476, 01Q3, 43771, 01Q4, 47308, 02Q1, 35742, 02Q2, 54494, 02Q3, 46808, 02Q4, 46984, 03Q1, 44546, 03Q2, 57414, 03Q3, 64027, 03Q4, 60280, 04Q1, 65968, 04Q2, 60198, 04Q3, 75418, 04Q4, 70704, 05Q1, 75315, 05Q2, 79976, 05Q3, 81045, 05Q4, 88472, 06Q1, 89476, 06Q2, 79467, 06Q3, 71675, 06Q4, 83122, 07Q1, 88691, 07Q2, 83769, 07Q3, 95826, 07Q4, 109749, 08Q1, 104286, 08Q2, 107346, 08Q3, 108392, 08Q4, 120859, 09Q1, 111408, 09Q2, 112423, 09Q3, 129991, 09Q4, 137453, 10Q1, 136128, 10Q2, 144239, 10Q3, 209242, 10Q4, 183498, 11Q1, 181025, 11Q2, 194277, 11Q3, 198723, 11Q4, 208655, 12Q1, 231908, 12Q2, 225258, 12Q3, 136332, 12Q4, 238616, 85, 274423, 92, 478655, 95, 393421, 97Q4, 29292, 98, 340428, 98Q1, 43607, 98Q2, 34535, 98Q3, 38609, 98Q4, 40436, 99Q1, 77096, 99Q2, 46548, 99Q3, 54421, 99Q4, 44992]
	at com.sapphire.etl.AERS_RECORD_COUNTS.AERSCaseCountDemo(CaseCountInQtr.java:81)
	... 21 more
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- AERSCaseCountDemo -->
  <testcase name="AERSCaseCounts" time="0.027" classname="com.sapphire.etl.AERS_RECORD_COUNTS">
    <failure type="java.lang.AssertionError" message="SELECT fda_rel_qtr,count FROM aers_stats group by fda_rel_qtr">
      <![CDATA[java.lang.AssertionError: SELECT fda_rel_qtr,count FROM aers_stats group by fda_rel_qtr
	at com.sapphire.etl.AERS_RECORD_COUNTS.AERSCaseCounts(CaseCountInQtr.java:50)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.AssertionError: null: lists don't have the same size expected [132] but found [130]
	at com.sapphire.etl.AERS_RECORD_COUNTS.AERSCaseCounts(CaseCountInQtr.java:43)
	... 21 more
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- AERSCaseCounts -->
</testsuite> <!-- Database Test on Win7 -->
