<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" total="10" passed="5">
  <reporter-output>
    <line>
      <![CDATA[SELECT count(*) FROM aers_demo where case_id is null]]>
    </line>
    <line>
      <![CDATA[Expected : [0]]]>
    </line>
    <line>
      <![CDATA[Actual : [0]]]>
    </line>
    <line>
      <![CDATA[SELECT distinct age_code FROM aers_demo]]>
    </line>
    <line>
      <![CDATA[Expected : [YR, MON, WK, DY, HR, DEC, MIN, SEC, '']]]>
    </line>
    <line>
      <![CDATA[Actual : [YR,  , MON, WK, DY, HR, DEC, M, F, 64, SEC, MIN, 85]]]>
    </line>
    <line>
      <![CDATA[SELECT count(*) FROM aers_demo where std_age_group = 'Not Available' AND age != '' AND age_code != '' AND age not like ('%-%') AND age not like ('%.%') AND age != 0 AND age != 00]]>
    </line>
    <line>
      <![CDATA[Expected : [0]]]>
    </line>
    <line>
      <![CDATA[Actual : [631]]]>
    </line>
    <line>
      <![CDATA[SELECT distinct gender_code FROM aers_demo]]>
    </line>
    <line>
      <![CDATA[Expected : [F, M, UNK, NS, U, '']]]>
    </line>
    <line>
      <![CDATA[Actual : [F,  , M, UNK, NS, null, YR, N, Y, U]]]>
    </line>
    <line>
      <![CDATA[SELECT distinct gender_dec FROM aers_demo]]>
    </line>
    <line>
      <![CDATA[Expected : null]]>
    </line>
    <line>
      <![CDATA[Actual : []]]>
    </line>
    <line>
      <![CDATA[SELECT count(*) FROM aers_demo where seriousness = 1 and ( outc_death= 0 and  outc_life_threat =0 and outc_hosp =0 and outc_disability=0 and outc_cong_anomaly=0  and outc_reqd_interv=0 and outc_other=0 and outc_none=0 and outc_rec=0 and outc_rx=0)]]>
    </line>
    <line>
      <![CDATA[Expected : [0]]]>
    </line>
    <line>
      <![CDATA[Actual : [0]]]>
    </line>
    <line>
      <![CDATA[SELECT count(*) FROM aers_demo where valid_from is null]]>
    </line>
    <line>
      <![CDATA[Expected : [0]]]>
    </line>
    <line>
      <![CDATA[Actual : [0]]]>
    </line>
    <line>
      <![CDATA[SELECT count(*) FROM aers_demo where valid_to is null]]>
    </line>
    <line>
      <![CDATA[Expected : [0]]]>
    </line>
    <line>
      <![CDATA[Actual : [13]]]>
    </line>
    <line>
      <![CDATA[SELECT count(*) FROM aers_demo where fda_date is null]]>
    </line>
    <line>
      <![CDATA[Expected : [0]]]>
    </line>
    <line>
      <![CDATA[Actual : [0]]]>
    </line>
    <line>
      <![CDATA[SELECT count(*) FROM aers_demo where isr_id is null]]>
    </line>
    <line>
      <![CDATA[Expected : [0]]]>
    </line>
    <line>
      <![CDATA[Actual : [0]]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="5263" started-at="2014-05-30T06:49:26Z" finished-at="2014-05-30T06:49:32Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5263" started-at="2014-05-30T06:49:26Z" finished-at="2014-05-30T06:49:32Z">
      <class name="com.sapphire.etl.AERSDemoVerify">
        <test-method status="PASS" signature="demoCASE_ID()[pri:0, instance:com.sapphire.etl.AERSDemoVerify@290fbc]" name="demoCASE_ID" duration-ms="632" started-at="2014-05-30T12:19:26Z" finished-at="2014-05-30T12:19:27Z">
          <reporter-output>
            <line>
              <![CDATA[SELECT count(*) FROM aers_demo where case_id is null]]>
            </line>
            <line>
              <![CDATA[Expected : [0]]]>
            </line>
            <line>
              <![CDATA[Actual : [0]]]>
            </line>
          </reporter-output>
        </test-method> <!-- demoCASE_ID -->
        <test-method status="FAIL" signature="demoCaseAgeCode()[pri:0, instance:com.sapphire.etl.AERSDemoVerify@290fbc]" name="demoCaseAgeCode" duration-ms="36" started-at="2014-05-30T12:19:27Z" finished-at="2014-05-30T12:19:27Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[SELECT distinct age_code FROM aers_demo]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: SELECT distinct age_code FROM aers_demo
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseAgeCode(AERSDemoVerify.java:352)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: null: lists don't have the same size expected [9] but found [13]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:537)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.sapphire.etl.AERSDemoVerify.demoCaseAgeCode(AERSDemoVerify.java:345)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[SELECT distinct age_code FROM aers_demo]]>
            </line>
            <line>
              <![CDATA[Expected : [YR, MON, WK, DY, HR, DEC, MIN, SEC, '']]]>
            </line>
            <line>
              <![CDATA[Actual : [YR,  , MON, WK, DY, HR, DEC, M, F, 64, SEC, MIN, 85]]]>
            </line>
          </reporter-output>
        </test-method> <!-- demoCaseAgeCode -->
        <test-method status="FAIL" signature="demoCaseAgeGroup()[pri:0, instance:com.sapphire.etl.AERSDemoVerify@290fbc]" name="demoCaseAgeGroup" duration-ms="4345" started-at="2014-05-30T12:19:27Z" finished-at="2014-05-30T12:19:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[SELECT count(*) FROM aers_demo where std_age_group = 'Not Available' AND age != '' AND age_code != '' AND age not like ('%-%') AND age not like ('%.%') AND age != 0 AND age != 00]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: SELECT count(*) FROM aers_demo where std_age_group = 'Not Available' AND age != '' AND age_code != '' AND age not like ('%-%') AND age not like ('%.%') AND age != 0 AND age != 00
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseAgeGroup(AERSDemoVerify.java:389)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: Lists differ at element [0]: 0 != 631 expected [0] but found [631]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.sapphire.etl.AERSDemoVerify.demoCaseAgeGroup(AERSDemoVerify.java:382)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[SELECT count(*) FROM aers_demo where std_age_group = 'Not Available' AND age != '' AND age_code != '' AND age not like ('%-%') AND age not like ('%.%') AND age != 0 AND age != 00]]>
            </line>
            <line>
              <![CDATA[Expected : [0]]]>
            </line>
            <line>
              <![CDATA[Actual : [631]]]>
            </line>
          </reporter-output>
        </test-method> <!-- demoCaseAgeGroup -->
        <test-method status="FAIL" signature="demoCaseGenderCode()[pri:0, instance:com.sapphire.etl.AERSDemoVerify@290fbc]" name="demoCaseGenderCode" duration-ms="36" started-at="2014-05-30T12:19:31Z" finished-at="2014-05-30T12:19:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[SELECT distinct gender_code FROM aers_demo]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: SELECT distinct gender_code FROM aers_demo
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseGenderCode(AERSDemoVerify.java:234)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: null: lists don't have the same size expected [6] but found [10]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:537)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.sapphire.etl.AERSDemoVerify.demoCaseGenderCode(AERSDemoVerify.java:227)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[SELECT distinct gender_code FROM aers_demo]]>
            </line>
            <line>
              <![CDATA[Expected : [F, M, UNK, NS, U, '']]]>
            </line>
            <line>
              <![CDATA[Actual : [F,  , M, UNK, NS, null, YR, N, Y, U]]]>
            </line>
          </reporter-output>
        </test-method> <!-- demoCaseGenderCode -->
        <test-method status="FAIL" signature="demoCaseGenderDEC()[pri:0, instance:com.sapphire.etl.AERSDemoVerify@290fbc]" name="demoCaseGenderDEC" duration-ms="41" started-at="2014-05-30T12:19:31Z" finished-at="2014-05-30T12:19:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[SELECT distinct gender_dec FROM aers_demo]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: SELECT distinct gender_dec FROM aers_demo
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseGenderDEC(AERSDemoVerify.java:273)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.sql.SQLException: Column Index out of range, 2 > 1. 
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ResultSetImpl.checkColumnBounds(ResultSetImpl.java:818)
	at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5651)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5570)
	at com.sapphire.etl.AERSDemoVerify.demoCaseGenderDEC(AERSDemoVerify.java:257)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[SELECT distinct gender_dec FROM aers_demo]]>
            </line>
            <line>
              <![CDATA[Expected : null]]>
            </line>
            <line>
              <![CDATA[Actual : []]]>
            </line>
          </reporter-output>
        </test-method> <!-- demoCaseGenderDEC -->
        <test-method status="PASS" signature="demoCaseSeriousness()[pri:0, instance:com.sapphire.etl.AERSDemoVerify@290fbc]" name="demoCaseSeriousness" duration-ms="29" started-at="2014-05-30T12:19:31Z" finished-at="2014-05-30T12:19:32Z">
          <reporter-output>
            <line>
              <![CDATA[SELECT count(*) FROM aers_demo where seriousness = 1 and ( outc_death= 0 and  outc_life_threat =0 and outc_hosp =0 and outc_disability=0 and outc_cong_anomaly=0  and outc_reqd_interv=0 and outc_other=0 and outc_none=0 and outc_rec=0 and outc_rx=0)]]>
            </line>
            <line>
              <![CDATA[Expected : [0]]]>
            </line>
            <line>
              <![CDATA[Actual : [0]]]>
            </line>
          </reporter-output>
        </test-method> <!-- demoCaseSeriousness -->
        <test-method status="PASS" signature="demoCaseValidFrom()[pri:0, instance:com.sapphire.etl.AERSDemoVerify@290fbc]" name="demoCaseValidFrom" duration-ms="36" started-at="2014-05-30T12:19:32Z" finished-at="2014-05-30T12:19:32Z">
          <reporter-output>
            <line>
              <![CDATA[SELECT count(*) FROM aers_demo where valid_from is null]]>
            </line>
            <line>
              <![CDATA[Expected : [0]]]>
            </line>
            <line>
              <![CDATA[Actual : [0]]]>
            </line>
          </reporter-output>
        </test-method> <!-- demoCaseValidFrom -->
        <test-method status="FAIL" signature="demoCaseValidTo()[pri:0, instance:com.sapphire.etl.AERSDemoVerify@290fbc]" name="demoCaseValidTo" duration-ms="33" started-at="2014-05-30T12:19:32Z" finished-at="2014-05-30T12:19:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[SELECT count(*) FROM aers_demo where valid_to is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: SELECT count(*) FROM aers_demo where valid_to is null
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDemoVerify.demoCaseValidTo(AERSDemoVerify.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: Lists differ at element [0]: 0 != 13 expected [0] but found [13]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.sapphire.etl.AERSDemoVerify.demoCaseValidTo(AERSDemoVerify.java:76)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[SELECT count(*) FROM aers_demo where valid_to is null]]>
            </line>
            <line>
              <![CDATA[Expected : [0]]]>
            </line>
            <line>
              <![CDATA[Actual : [13]]]>
            </line>
          </reporter-output>
        </test-method> <!-- demoCaseValidTo -->
        <test-method status="PASS" signature="demoFDA_date()[pri:0, instance:com.sapphire.etl.AERSDemoVerify@290fbc]" name="demoFDA_date" duration-ms="28" started-at="2014-05-30T12:19:32Z" finished-at="2014-05-30T12:19:32Z">
          <reporter-output>
            <line>
              <![CDATA[SELECT count(*) FROM aers_demo where fda_date is null]]>
            </line>
            <line>
              <![CDATA[Expected : [0]]]>
            </line>
            <line>
              <![CDATA[Actual : [0]]]>
            </line>
          </reporter-output>
        </test-method> <!-- demoFDA_date -->
        <test-method status="PASS" signature="demoISR_ID()[pri:0, instance:com.sapphire.etl.AERSDemoVerify@290fbc]" name="demoISR_ID" duration-ms="28" started-at="2014-05-30T12:19:32Z" finished-at="2014-05-30T12:19:32Z">
          <reporter-output>
            <line>
              <![CDATA[SELECT count(*) FROM aers_demo where isr_id is null]]>
            </line>
            <line>
              <![CDATA[Expected : [0]]]>
            </line>
            <line>
              <![CDATA[Actual : [0]]]>
            </line>
          </reporter-output>
        </test-method> <!-- demoISR_ID -->
      </class> <!-- com.sapphire.etl.AERSDemoVerify -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
