<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PDWIVEDI" name="com.sapphire.etl.AERSDrugVerify" tests="5" failures="0" timestamp="28 May 2014 14:28:46 GMT" time="8.945" errors="2">
  <testcase name="drugCleaned_GenericName" time="3.438" classname="com.sapphire.etl.AERSDrugVerify">
    <error type="java.lang.AssertionError" message="SELECT count(*) FROM aers.aers_drugs where drug_cleaned is not null and generic_name is null or generic_name=&#039;&#039;">
      <![CDATA[java.lang.AssertionError: SELECT count(*) FROM aers.aers_drugs where drug_cleaned is not null and generic_name is null or generic_name=''
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDrugVerify.drugCleaned_GenericName(AERSDrugVerify.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: Lists differ at element [0]: 0 != 17288 expected [0] but found [17288]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.sapphire.etl.AERSDrugVerify.drugCleaned_GenericName(AERSDrugVerify.java:136)
	... 24 more
]]>
    </error>
  </testcase> <!-- drugCleaned_GenericName -->
  <testcase name="drugRole_Dec" time="0.026" classname="com.sapphire.etl.AERSDrugVerify"/>
  <testcase name="drugCleaned_Null" time="5.421" classname="com.sapphire.etl.AERSDrugVerify">
    <error type="java.lang.AssertionError" message="SELECT count(*) FROM aers.aers_drugs where drug_cleaned is null">
      <![CDATA[java.lang.AssertionError: SELECT count(*) FROM aers.aers_drugs where drug_cleaned is null
	at org.testng.Assert.fail(Assert.java:83)
	at com.sapphire.etl.AERSDrugVerify.drugCleaned_Null(AERSDrugVerify.java:173)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: Lists differ at element [0]: 0 != 1960 expected [0] but found [1960]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.sapphire.etl.AERSDrugVerify.drugCleaned_Null(AERSDrugVerify.java:168)
	... 24 more
]]>
    </error>
  </testcase> <!-- drugCleaned_Null -->
  <testcase name="drugISR_ID" time="0.033" classname="com.sapphire.etl.AERSDrugVerify"/>
  <testcase name="drugRole_Code" time="0.027" classname="com.sapphire.etl.AERSDrugVerify"/>
</testsuite> <!-- com.sapphire.etl.AERSDrugVerify -->
